
package ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente._5_0_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T17:47:52.381-03:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "BGBAResultadoOperacionFalla", targetNamespace = "http://ws.bancogalicia.com.ar/webservices/globales/bgbaresultadooperacion/2_0_0")
public class BGBAResultadoOperacionFalla extends Exception {

    private ar.com.bancogalicia.ws.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla bgbaResultadoOperacionFalla;

    public BGBAResultadoOperacionFalla() {
        super();
    }

    public BGBAResultadoOperacionFalla(String message) {
        super(message);
    }

    public BGBAResultadoOperacionFalla(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BGBAResultadoOperacionFalla(String message, ar.com.bancogalicia.ws.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla bgbaResultadoOperacionFalla) {
        super(message);
        this.bgbaResultadoOperacionFalla = bgbaResultadoOperacionFalla;
    }

    public BGBAResultadoOperacionFalla(String message, ar.com.bancogalicia.ws.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla bgbaResultadoOperacionFalla, java.lang.Throwable cause) {
        super(message, cause);
        this.bgbaResultadoOperacionFalla = bgbaResultadoOperacionFalla;
    }

    public ar.com.bancogalicia.ws.webservices.globales.bgbaresultadooperacion._2_0_0.BGBAResultadoOperacionFalla getFaultInfo() {
        return this.bgbaResultadoOperacionFalla;
    }
}
