package ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente._5_0_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T17:47:52.404-03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ConsultaCliente",
                  wsdlLocation = "http://desaosb.bancogalicia.com.ar:8003/consultacliente/5_0_1/anonimo?wsdl",
                  targetNamespace = "http://ws.bancogalicia.com.ar/webservices/abmcinfoclientes/consultacliente/5_0_0")
public class ConsultaCliente_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.bancogalicia.com.ar/webservices/abmcinfoclientes/consultacliente/5_0_0", "ConsultaCliente");
    public final static QName ConsultaCliente = new QName("http://ws.bancogalicia.com.ar/webservices/abmcinfoclientes/consultacliente/5_0_0", "ConsultaCliente");
    static {
        URL url = null;
        try {
            url = new URL("http://desaosb.bancogalicia.com.ar:8003/consultacliente/5_0_1/anonimo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaCliente_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://desaosb.bancogalicia.com.ar:8003/consultacliente/5_0_1/anonimo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaCliente_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaCliente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCliente_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultaCliente_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaCliente_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaCliente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultaCliente
     */
    @WebEndpoint(name = "ConsultaCliente")
    public ConsultaCliente getConsultaCliente() {
        return super.getPort(ConsultaCliente, ConsultaCliente.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCliente
     */
    @WebEndpoint(name = "ConsultaCliente")
    public ConsultaCliente getConsultaCliente(WebServiceFeature... features) {
        return super.getPort(ConsultaCliente, ConsultaCliente.class, features);
    }

}
