
package ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente._5_0_1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T17:47:52.335-03:00
 * Generated source version: 3.2.4
 *
 */
public final class ConsultaCliente_ConsultaCliente_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.bancogalicia.com.ar/webservices/abmcinfoclientes/consultacliente/5_0_0", "ConsultaCliente");

    private ConsultaCliente_ConsultaCliente_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultaCliente_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ConsultaCliente_Service ss = new ConsultaCliente_Service(wsdlURL, SERVICE_NAME);
        ConsultaCliente port = ss.getConsultaCliente();

        {
        System.out.println("Invoking buscarClientePorDatosBasicos...");
        ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.buscarclientepordatosbasicosrequest._2_0_0.BuscarClientePorDatosBasicos _buscarClientePorDatosBasicos_parameters = null;
        try {
            ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.buscarclientepordatosbasicosresponse._2_0_0.BuscarClientePorDatosBasicosResult _buscarClientePorDatosBasicos__return = port.buscarClientePorDatosBasicos(_buscarClientePorDatosBasicos_parameters);
            System.out.println("buscarClientePorDatosBasicos.result=" + _buscarClientePorDatosBasicos__return);

        } catch (BGBAResultadoOperacionFalla e) {
            System.out.println("Expected exception: BGBAResultadoOperacionFalla has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerCliente...");
        ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.obtenerclienterequest._4_0_0.ObtenerCliente _obtenerCliente_parameters = null;
        try {
            ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.obtenerclienteresponse._4_0_0.ObtenerClienteResult _obtenerCliente__return = port.obtenerCliente(_obtenerCliente_parameters);
            System.out.println("obtenerCliente.result=" + _obtenerCliente__return);

        } catch (BGBAResultadoOperacionFalla e) {
            System.out.println("Expected exception: BGBAResultadoOperacionFalla has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscarClientePorProducto...");
        ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.buscarclienteporproductorequest._2_0_0.BuscarClientePorProducto _buscarClientePorProducto_parameters = null;
        try {
            ar.com.bancogalicia.ws.webservices.abmcinfoclientes.consultacliente.buscarclienteporproductoresponse._2_0_0.BuscarClientePorProductoResult _buscarClientePorProducto__return = port.buscarClientePorProducto(_buscarClientePorProducto_parameters);
            System.out.println("buscarClientePorProducto.result=" + _buscarClientePorProducto__return);

        } catch (BGBAResultadoOperacionFalla e) {
            System.out.println("Expected exception: BGBAResultadoOperacionFalla has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerClasificacionSegunMovimientos...");
        ar.com.bancogalicia.ws.webservices.consultacliente.obtenerclasificacionsegunmovimientosrequest._2_0_0.ObtenerClasificacionSegunMovimientos _obtenerClasificacionSegunMovimientos_parameters = null;
        try {
            ar.com.bancogalicia.ws.webservices.consultacliente.obtenerclasificacionsegunmovimientosresponse._2_0_0.ObtenerClasificacionSegunMovimientosResult _obtenerClasificacionSegunMovimientos__return = port.obtenerClasificacionSegunMovimientos(_obtenerClasificacionSegunMovimientos_parameters);
            System.out.println("obtenerClasificacionSegunMovimientos.result=" + _obtenerClasificacionSegunMovimientos__return);

        } catch (BGBAResultadoOperacionFalla e) {
            System.out.println("Expected exception: BGBAResultadoOperacionFalla has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerRelacionesCliente...");
        ar.com.bancogalicia.ws.webservices.consultacliente.obtenerrelacionesclienterequest._2_0_0.ObtenerRelacionesCliente _obtenerRelacionesCliente_parameters = null;
        try {
            ar.com.bancogalicia.ws.webservices.consultacliente.obtenerrelacionesclienteresponse._2_0_0.ObtenerRelacionesClienteResult _obtenerRelacionesCliente__return = port.obtenerRelacionesCliente(_obtenerRelacionesCliente_parameters);
            System.out.println("obtenerRelacionesCliente.result=" + _obtenerRelacionesCliente__return);

        } catch (BGBAResultadoOperacionFalla e) {
            System.out.println("Expected exception: BGBAResultadoOperacionFalla has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
